- .github/workflows/km-ci-workflow.yaml
- cloud/azure/L0-image.pkr.hcl
- cloud/azure/scripts/L0-image-provision.sh
- make/images.mk
- tests/packer/Makefile
- tests/packer/km-aws-test.pkr.hcl
- tests/packer/km-az-test.pkr.hcl
- tests/packer/scripts/km-test.sh
run kkm test in packer driven VMs.
> Cleanup L0 image pkr.hcl and kkm packer tests

- container-runtime/podman_config.sh
Set the proper security context on /dev/kkm so podman can run containers using kkm.
Change the ownership and group of directories created when we create ~/.config/containers/containers.conf
Tested by running a vagrant fedora box using the changed podman_config.sh and then verifying that
podman run --rm -it --runtime krun kontainapp/runenv-dweb:latest sh
would work.
And did "ls -l" on the components in ~/.config/containers/containers.conf has proper group and user
assigned.
> Add selinux policy changes for /dev/kkm

- docs/quick-start-guide.md
My attempt at quick start guide. Let me know what you think.
> WIP: Serge/quick start

- cloud/k8s/deploy/k8s-deploy.sh
- cloud/k8s/deploy/k8s-deploy.yaml
- cloud/k8s/deploy/shim/shim.go
Issues:
- Privileged
- DaemonSet logic should be in InitContainer, not main container (per Google example)
> Kontain RuntimeClass for containerd in Kubernetes

- cloud/k8s/deploy/k8s-deploy.sh
- cloud/k8s/deploy/k8s-deploy.yaml
> Add udev config for KVM to k8s install DaemonSet

- docs/demo-script.md
- km/km.h
- km/km_cpu_init.c
- km/km_hcalls.c
- km/km_init_guest.c
- km/km_main.c
- km/km_signal.c
- payloads/node/platform:f35_skip
- payloads/node/scripts/test-run.sh
- runtime/clone_km.s
- tests/Makefile
- tests/hello_2_loops_test.c
- tests/km_core_tests.bats
- tests/sigaltstack_test.c
- tests/test-fedora.dockerfile
- tests/var_storage_test.cpp
Merged #1414 as squash, but it is beneficial to keep those commits separate, so redoing it here.
> Dup of PR 1414

- cloud/k8s/tools/README.md
- cloud/k8s/tools/hack_node.yaml
First tool is a node file system examination tool.
> Start a toolkit for Kubernetes

- cloud/k8s/deploy/cm-install-lib.yaml
- cloud/k8s/deploy/kontain-deploy/base/kontain-deploy.yaml
This will allow sanjay to publish consistently numbered release URL's.
> Create a v0.9.3 release that references itself in the k8s YAML files

- demo/gpu/Notes.md
> WIP: Initial notes for GPU thinking

- .gitmodules
These are the Amazon packer scripts used to creare ECS and EKS AMI's.
We augment these with the KKM driver and KM binaries.
> Add amazon AMI creation project forks. Used to build release AMI's.

- demo/aws/README.md
> Work for supporting AWS ECS

- .gitmodules
Now as log4j, spring-boot, and tesnsorflow apps are in km-demo repository, and the new images are published, we can remove them from the main repo.
> remove demo sub-modules and log4j, spring-boot, and tensorflow demos

- km/km_exec.c
- km/km_exec_fd_save_recover.c
- km/km_filesys.c
- km/km_filesys_private.h
> Fix concurrency errors in km_filesys around inuse and next internal fd

- README.md
Added comment with link to https://kontainapp.github.io/guide/
> DOC ONLY-edits for adding application user guide link to readme

- km-releases/kontain-install.sh
added amzn to list of supported distros we can install to
> #1481- added amzn to list of supported distros we can install to

- README.md
switched out use of /latest to /current as /latest has issues
> DOC ONLY-changed latest to current for install of Kontain

- .github/workflows/km-ci-workflow.yaml
- docs/ecs/proposal.md
Integrate file marker based hack to go with label hack.
> File marker based KM trigger

- tools/faktory/go.mod
- tools/faktory/go.sum
Change to 1.4.13 to squelch depenabot
> containerd version

- km/load_elf.c
`my_mmap` sounds like something in a kid's toy project. Change the name of the function to something a bit more serious sounding.
> cleanup comments and function name in load_elf.c

- km/km_exec.c
- km/km_fork.c
close vcpus, machine and them kvm fd in this specific order.
> change close order during fork and exec

- km/km_filesys.c
- km/km_filesys.h
- km/km_fork.c
> clear state in child

- km/km.h
- km/km_coredump.c
- km/km_coredump.h
- km/km_snapshot.c
> recover brk/tbrk from snapshot

- .github/workflows/km-ci-workflow.yaml
- .github/workflows/release.yaml
- Makefile
- cloud/k8s/deploy/kontain-deploy/overlays/ci/set_ci_env.yaml
In CI we no longer build dynamic run. Instead, static run is built and used directly.
> Ez leka/use static krun

- .github/workflows/km-ci-cleanup.yaml
Just making sure the CI runners VMs are cleanup after a week
> Trivial: CI cleanup - vpc name, syntax

- lib/libkontain/Makefile
> create the right dir

- tests/km_core_tests.bats
This is about issue 993 .
* On my local system `threads_basic_tsd` worked fine for both `kvm` and `kkm` so I'm reenabling it.
> WIP: Reenable some tests.

- tests/km_core_tests.bats
test ran 200 iteration on kkm in a vm.
> enable threads_exit_grp test on kkm

- km/km_filesys.c
- tests/utimensat_test.c
> handle null file name in utimensat syscall

- tests/snapshot_test.c
Trying this on Fedora 36 - gcc version 12.1.1. Turns out the structure assignment uses xmm0 register. Since the test value was assigned to the xmm0 register before the structure assignment, by the time snapshot is done the value in xmm0 is erased, and the further check after restore fails.
Moved the structure assignment to before setting xmm0 register test value, which is now done right before the snapshot call. No changes in km or anywhere else, just in the test program itself.
> Clean FP state check in snapshot test

- .gitignore
- cloud/k8s/deploy/build_overlays.sh
- cloud/k8s/deploy/kontain-deploy/base/cm-install-lib.yaml
- cloud/k8s/deploy/kontain-deploy/base/kontain-deploy.yaml
Please see #1590 for more details.
> #1590 - using current_release.txt to read release artifact URL programmatically

- km/km.h
- km/km_cpu_init.c
- km/km_fork.c
- km/km_gdb_stub.c
- km/km_vcpu_run.c
Fixes https://github.com/kontainapp/km/issues/434
> Eliminate forced exit

- .github/workflows/km-ci-workflow.yaml
codeql now takes container from azure registry as do all other builds
> Ez leka/codeql

- km/km_cpu_init.c
- km/km_management.c
- tests/test_helper.bash
fix in the exit / vcpu stop logic. Allow for vcpu being interrupted while exiting.
> vcpu stop fix

- .github/workflows/km-ci-workflow.yaml
- make/images.mk
- payloads/node/.dockerignore
- payloads/node/Makefile
- payloads/node/scripts/test-run.sh
- payloads/node/test-fedora.dockerfile
1. Fixed brocken node payload test-all
2. added cleanup when creating testenv-image
3. added dependencies on tests for stoping/termination cloud runners
> Ez leka/test all

- km/gdb/list.gdb
macros to help look at coredump.
> show_vcpus and show_guest_args macros

- README.md
- tests/scripts/coverage/coverage.sh
- tests/scripts/coverage/upload-coverage.sh
Added dynamic coverage badge to README.md
> Ez leka/coverage badges

- .github/workflows/km-ci-coverage.yaml
- .github/workflows/km-ci-workflow.yaml
- .github/workflows/km-valgrind.yaml
- .github/workflows/stop-cloud-runners.yaml
- tests/Makefile
needs doe snot automatically propagate to callable workflow. Have to pass it explicitly
> Ez leka/stop runner fix

- README.md
Made simple modifications to readme.md to emphasize Kontain running existing Docker Containers and also added the animations on how to use Kontain and install Kontain.
> DOC ONLY - Mods to readme.md to emphasize Kontain running existing Docker Containers and animation on how to use

- km/km_mem.c
KM page tables are not required when virtualization device is kkm.
> initialize page tables only on kvm

- .github/actions/configure-krun/action.yaml
- .github/workflows/km-ci-workflow.yaml
- .github/workflows/release.yaml
- Makefile
- container-runtime/Makefile
- tools/bin/create_release.sh
fixes [Issues 1426](https://github.com/kontainapp/km/commit/df296266549c392e46c051277295534a745c7389)
> Put static KRUN in to full release

- container-runtime/docker_config.sh
Fixes https://github.com/kontainapp/km/issues/1465
> correct check for docker

- tests/km_core_tests.bats
keep snapshots and cores around in case of failure
> TRIVIAL: keep snap and core for snapshot failures

- .github/workflows/km-ci-workflow.yaml
- .github/workflows/release.yaml
- payloads/demo-dweb/dweb/cpuid.c
- payloads/demo-dweb/dweb/dweb.c
- tools/hashicorp/Makefile
fixes #1633 
fixes #1579
fixes #1578 
fixes #1467 
fixes #1509
fixes #1508
> Ez leka/add eks ecs ami builds

- tests/km_core_tests.bats
Fixes recent CI failures in snapshot tests
> Change wait in snapshot test from process exists to mgt pipe exists

- tests/hello_2_loops_test.c
use atomic + and - to wait for detached threads to finish
> fix detached threads test

- tests/cmd_for_attach_test.gdb
These were introduced in my previous checkin.
> Fix some very dumb errors in cmd_for_attach_test.gdb

- km/km_main.c
- tools/bin/create_release.sh
- tools/hashicorp/scripts/fedora.install_km.sh
- tools/hashicorp/scripts/ubuntu.install_km.sh
- recompute select timeout every time - select can change it
- containerd shim location for release
- add jq for release
> various fixes

- Makefile
- cloud/k8s/shim/Makefile
- cloud/k8s/shim/krun-label-trigger.go
- cloud/k8s/shim/krun.go
- cloud/k8s/shim/shim.go
- tools/bin/create_release.sh
add another shim executable to use the krun-label-trigger
> shim for krun-label-trigger

- tests/km_core_tests.bats
Removed too much in the previous PR
> skip popen test for dynamic case

- docs/valgrind.md
- km/km_hcalls.c
Also add some brief notes to docs/valgrind.md explaining how to run bats tests with valgrind.
> Add missing payload address translations in io_submit_hcall().

- km/km_coredump.c
> Address code scan compain

- km/km_hcalls.c
valgrind found some problems in km sendmsg() code.
> Fix some uninitialized fields in the msghdr structure

- runtime/chk_stub_km.c
Things I discovered pytorch needs
> extra libs for pytorch

- km/km_elf.h
- km/km_musl_related.c
- km/load_elf.c
the code is very simple like paul said.
> add glibc symbol support

- tests/km_core_tests.bats
In the wonderful cloud environment our tests are treated to all manner of process scheduling preemptions.
In this case I thing the simple html server in the test was timed out by km_with_timeout before we finished the loop where we take snapshots and run curl against the html server.
We try to detect that km_cli or curl failed because the html server process timed out.  If that is what happened we end the test but call it successul.
If the html srver is still running then we assume there was some other failure and we do fail the test.
We will just need to wait for mr cloud to grace us with more kookie scheduling preemptions to see if this change helps.
> Change bats continue_after_snapshot test to discover if html has timed out

- .github/workflows/release.yaml
- Makefile
- tools/hashicorp/Makefile
- tools/release/gh_release.sh
make release using github cli (pre-installed in github runners)
> make release using github cli

- Makefile
- make/locations.mk
- payloads/java/buildenv-fedora.dockerfile
- payloads/java/test-fedora.dockerfile
- payloads/node/buildenv-fedora.dockerfile
- payloads/node/link-km.sh
- tests/buildenv-fedora.dockerfile
https://github.com/kontainapp/km/issues/1440
> Fedora 35 build environment
