kontainapp/km

tools/faktory/go.mod
tools/faktory/go.sum

To address github security notice upgraded containerd version used in faktory.
Caveat - the code seems to be broken regardless of the version, `make test` fails. I only confirmed that it fails the same way. Need to decide what we do with this going forward.

upgrade containerd to newer version

---

km/km_coredump.h
km/km_signal.c
tests/snapshot_test.c

Snapshots were not preserving the SA_RESTORER flag but not the address.
This caused signal handlers created with the SA_RESTORER flag to attempt
to return to 0. We found this in the SpringBoot demo, but it effected more
than that.
The test excersizes the condition. Verified that the test fails without
the changes to KM.

Preserve SA_RESTORER address in snapshots

---

.github/workflows/release.yaml
cloud/azure/scripts/vagrant-box.sh
make/locations.mk

Turns out SRC_BRANCH isn't set correctly when a github action is triggered with tag push. 
Tested by applying v0.1-edge tag. Will apply v0.9.0 tag when merged

Fix to the release pipeline

---

km-releases/kontain-install.sh

Turns out github release artifacts URLs are not what I was expecting. The _latest_ release is at
```
https://github.com/kontainapp/km/releases/latest/download/kontain.tar.gz
```
while accessed by tag (say _v0.9.0_) the URL is:
```
https://github.com/kontainapp/km/releases/download/v0.9.0/kontain.tar.gz
```
Note transposition of _`latest/download`_ vs _`download/v0.9.0`_.
Access to individual files in the repo, OTOH, is more as expected
```
https://raw.githubusercontent.com/kontainapp/km/latest/<path_in_km>
https://raw.githubusercontent.com/kontainapp/km/v0.9.0/<path_in_km>
```
I updated the release document too

fix release URL

---

.github/workflows/km-ci-workflow.yaml
cloud/azure/Makefile

Turns out this timeout is in `az acr run ...` not in the workflow.

Increase CI image purge timeout to 30 mins (1800 sec)

---

container-runtime/podman_config.sh
demo/faktory/java/README.md
demo/spring-boot/Makefile
demo/spring-boot/README.md
demo/spring-boot/test/runperf.sh
demo/test-app/Makefile
demo/test-app/README.md
docs/demo-script.md
payloads/busybox/runenv.dockerfile
payloads/demo-dweb/dweb/Makefile
payloads/java/Makefile
payloads/java/runenv.dockerfile
payloads/python/Makefile
payloads/python/link-km.sh
payloads/python/scripts/flask/Dockerfile
payloads/python/scripts/flask/Makefile
payloads/python/scripts/flask/faktory_prepare.sh
payloads/python/scripts/flask/faktory_run_build.sh
payloads/python/scripts/flask/faktory_stem.dockerfile
payloads/python/scripts/micro_srv.py
tools/faktory/Makefile
tools/faktory/README.md
tools/faktory/docs/HOWTO.md
tools/faktory/tests/flask/assets/Dockerfile
tools/faktory/tests/flask/flask_test.go
tools/faktory/tests/java/assets/Dockerfile
tools/faktory/tests/java/java_test.go

Looked for `--device=/dev/kvm` and such everywhere, and change to `--runtime=krun` where appropriate. 
One noted area where is is *not* appropriate is our tests directory and corresponding test targets. In these cases we assume we are testing newly build km and we call in explicitly with the specific arguments.
In demos and such we should use the runtime.

use --runtime=krun in docs, scripts and such

---

.github/workflows/km-ci-workflow.yaml
payloads/Makefile

Nightly tests run `make validate-runenv-withk8s`. The nightly cluster is configured with with the kontaind, allowing the /dev/kvm access to the pods, and mount /opt/kontain/bin/km into the pods, not --runtime=krun. Our new demo-runenv-image do not support that as nothing inserts KM into the execution path.
Disable this step for now, until we figure out how to enable krun runtime on AKS
https://github.com/kontainapp/km/issues/1326

disable validate-runenv-withk8s

---

.github/workflows/km-ci-workflow.yaml
docs/build.md
docs/user-guide.md
make/images.mk
tests/packer/km-aws-test.pkr.hcl
tests/packer/km-az-test.pkr.hcl
tests/packer/scripts/gather-logs.sh

Make packer driven CI steps run in parallel.
Add log gathering if something fails - not really tested as nothing failed after adding these.
Disable KKM packer driven run for now, until KKM setup on Fedora (selinux related) is complete - see `km-krun-kkm-validate-runenv` step in `km-ci-workflow.yaml`

more parallel CI jobs

---

container-runtime/podman_config.sh

apt-get doesn't retry if another instance is currently running so we have an apt-get wrapper function that retries.

Add a shell function that retries apt-get until the lock file is available

---

docs/debugging-guide.md
docs/user-guide.md

Porting debugging content from User Guide. Only one section was missing. Once this change is approved, I will proceed with removing debugging content from the User Guide, per issue #1305

Add Analyzing KM Core Dumps

---

container-runtime/podman_config.sh

podman_config.sh will create ~/.config/containers/containers.conf from scratch if it
doesn't exist.  Then the code would drop down and verify that needed contents were
there and print messages.  If we create the file from scratch don't issue messages saying
configuration is present.  It confuses people.

Don't verify a containers.conf file that we created from scratch.

---

container-runtime/podman_config.sh
km-releases/kontain-install.sh
tools/bin/create_release.sh

Built files (like km) may be built on machine with or without selinux.
And, these same files may be installed on machines with or with selinux.
So, it is not important to propagate file contexts as part of building a release.
But we always install the contexts if the install target has selinux enabled.
We also need to set a file's selinux context as part of a build so that we
can test on the build machine.

Assign selinux file contexts at install time

---

.github/workflows/release.yaml

Fix the problem where docker doesn't know about krun.

Add podman_config and docker_config to the smoke test in release.yaml

---

cloud/azure/scripts/vagrant-box.sh

vagrant-box.sh was using "git checkout -b ${SRC_BRANCH}"  to get the source to
produce released versions of our fedora and ubuntu boxes.
-b created an new branch with the same name as the release branch.
We really wanted to switch to the branch we want to release.
This was discovered when a new target was added to a makefile and this
script tried to use the new target but the new branch from master didn't
have the target causing the make to fail.

vagrant box build script wasn't using the correct source code

---

docs/kubernetes/quickstart.md

Updated tip load local docker images into Minikube without pv.

DOC ONLY-updated tip to load Docker images into Minikube

---

payloads/busybox/Makefile
payloads/dynamic-base-large/Makefile
payloads/dynamic-base/Makefile

Turns out (thanks Sanjay!) busybox runenvs were not published, because we haven't defined `RUNENV_TAG` in Makefiles. This fixes it. As for v0.9.1 - I simply published the images manually.

publish busybox runenvs

---

demo/spring-boot/README.md
demo/test-app/.gitignore
demo/test-app/Dockerfile
demo/test-app/Makefile
demo/test-app/README.md
tools/hashicorp/build_tensorflow/Makefile
tools/hashicorp/build_tensorflow/Vagrantfile

Turns out some steps in snapshot demos were incorrect, fixing that. Springboot should be good now.
However tensorflow is still broken after switch to new version of python (3.9).

fixes for snapshot demos

---

cloud/k8s/deploy/cm-containerd-install.yaml
cloud/k8s/deploy/cm-crio-install.yaml
cloud/k8s/deploy/cm-install-lib.yaml
cloud/k8s/deploy/kontain-deploy.yaml

Assign Kontain runtime install daemonset to 'kube-system' namespace

---

.github/workflows/km-ci-workflow.yaml
cloud/k8s/deploy/README.md
cloud/k8s/deploy/cm-install-lib.yaml
cloud/k8s/deploy/kontain-deploy/base/kontain-deploy.yaml
cloud/k8s/deploy/kontain-deploy/base/kustomization.yaml
cloud/k8s/deploy/kontain-deploy/ci/kustomization.yaml
cloud/k8s/deploy/kontain-deploy/ci/set_ci_env.yaml

This PR enhances the `km-build` step of the CI pipeline to create the release files (`kontain.tar.gz` and `kontain_bin.tar.gz`) and to save these files as build artifacts that can be used by other steps in the pipeline
The `minikube-testing` step has been changed to download these artifacts and to start a python based HTTP server to make these artifacts available via `curl`.
Finally, a kustonization for the `kontain-deploy.yaml` modifies the release download url to use this local server.
Create release binaries in the pipeline to be consumed by other steps, in particular the minikube based kubernetes tests.
Fixes #1385

Use currently built binaries in minikube tests

---

tests/buildenv-fedora.dockerfile

The nix tool is used by crun to build the static binary. We need to install nix on the
buildenv image for use on the CI. See https://nixos.org/ for details on nix in interested.

Add nix to buildenv.

---

docs/demo-script.md
km/km.h
km/km_cpu_init.c
km/km_hcalls.c
km/km_init_guest.c
km/km_main.c
km/km_signal.c
payloads/node/platform:f35_skip
payloads/node/scripts/test-run.sh
runtime/clone_km.s
tests/Makefile
tests/hello_2_loops_test.c
tests/km_core_tests.bats
tests/sigaltstack_test.c
tests/test-fedora.dockerfile
tests/var_storage_test.cpp

Fedora 35 brings in glibc-2.34, which uses clone3() and dynamic stack size. This makes changes to support theses.
Tested manually running tests on Fedora 35. Separate clone3() test isn't implemented s musl has no wrapper for it.
There are still some other failures on Fedora 35 static glibc tests so this is not fully done yet.

clone3() and changes in sigaltstack to work with glibc 2.34

---

.github/workflows/km-ci-workflow.yaml

Fixes #1422 
See https://github.com/kontainapp/km/actions/runs/1552882621warning annotation.

remove obsolete artifact upload

---

.github/workflows/release.yaml

Static krun in binary release (only). Messy. Different logic than workflow yaml. Will open an issue to align this and workflow yaml later, but this is needed to move k8s effort forward.

Update release.yaml to include static krun in binary release

---

cloud/k8s/deploy/kontain-deploy/base/kontain-deploy.yaml

v0.1-edge didn't get built, and I'm not sure how much sense that makes. Make KM use the v0.9.2 release bits by default. This picks up the static KRUN bits we need for k8s installs.

Update kontain-deploy.yaml to use v0.9.2 release bits

---

km/km_hcalls.c

I turns out `write(fd, NULL, 0)` is supposed to succeed and return 0. So out check for the args is too zealous. And yes, node v16 does make such calls.
Regular tests. Also specific test with node v16 now pass. There are more issues there so node isn't ready yet, but I thought this is important on its own.

relax {p}read/write check for zero buf

---

.github/workflows/km-ci-workflow.yaml
.github/workflows/release.yaml

The container `nixos/nix:latest` was upgraded from 2.3.12 to 2.5.0 on 12/14/20211 and our CI step 'krun-static-build` promptly broke. So did upstream. There are two possible ways to fix this:
* add `--extra-experimental-features nix-command` to nix invocations in `km-ci-workflow.yaml` and `release.yaml`.
* fix the `nixos/nix` container version to the last working version.
Upstream CRUN choose door number 2, fix the container version to the last working verson (2.3.12) so that's what we'll do.
Fixes #1430

Fix 'nixos/nix' container version to fix CI failures in nix calls

---

.clang-format
km/gdb_kvm_x86_64.c
km/km.h
km/km_coredump.h
km/km_filesys_private.h
km/km_gdb_stub.c
km/km_musl_related.c
km/x86_cpu.h

Upgraded my local Linux system from Fedora 33 to Fedora 34. That upgraded me to clang-format 12 which gave a bunch more checks. This is fixes from running `clang-format -i km/*.h km/*.c`.

clang-format 12 updates

---

demo/spring-boot/Makefile
demo/spring-boot/README.md
demo/spring-boot/kontain.dockerfile
demo/spring-boot/snap_kontain.dockerfile
payloads/busybox/.gitignore
payloads/busybox/Makefile

Mostly documentation and snapshot container dockerfile. Minor cleanup in runenv-images - add `/tmp`to the base so no ned to add it separately for all payloads.

make snapshot kontainer for spingboot demo

---

payloads/node/.dockerignore
payloads/node/skip_unknown_hang

Added files for one test.
Skip two more - they pass on the desktop and in the CI other than the new nightly cluster, suspecting just not enough time

fix testenv for node

---

demo/spring-boot/kontain.dockerfile
payloads/Makefile
payloads/dynamic-base-large/Makefile
payloads/dynamic-base-scratch/Makefile
payloads/dynamic-base-scratch/buildenv-fedora.dockerfile
payloads/dynamic-base-scratch/demo-runenv.dockerfile
payloads/dynamic-base-scratch/runenv.dockerfile
payloads/dynamic-base-scratch/test-fedora.dockerfile
payloads/java-shell/Makefile
payloads/java-shell/buildenv-fedora.dockerfile
payloads/java-shell/demo-runenv.dockerfile
payloads/java-shell/runenv.dockerfile
payloads/java-shell/test-fedora.dockerfile
payloads/java/runenv.dockerfile

The jdk runenv is now shell-less. It is used as base for log4j exploit demo, which makes the exploit fail one steps earlier - since there is no shell to execute.
To get the jdk with shell use jdk-shell runenv. This one is used for springboot demo.

Add shell-less dynamic base and jdk

---

.github/workflows/km-ci-workflow.yaml

CI: run minikube tests before sending status

---

.github/workflows/release.yaml

@gnode1 If you do a new release this week, please include this.

add kkm.run to binary release. helpful for EKS.

---

README.md
cloud/azure/scripts/L0-image-provision.sh
cloud/azure/scripts/vagrant-box.sh
docs/FAQ.md
docs/user-guide.md
docs/vms_packer_in_ci_and_more.md
tools/hashicorp/Makefile
tools/hashicorp/box_images_templates/ubuntu2004.pkrvars.hcl
tools/hashicorp/scripts/ubuntu.install_km.sh
tools/hashicorp/test_ami_upload.pkr.hcl
tools/hashicorp/test_box_upload.pkr.hcl

Ubuntu 2010 is deprecated. Our release box for ubuntu didn't build for v0.9.4 because repositories are closed. We also use 2010 in some internal builds. I'm replacing it with 20.04 which is LTS. Also rebuilding the base image for tests.
The failure was hidden, hopefully it won't be any more

switch to ubuntu 20.04

---

tests/buildenv-fedora.dockerfile

We are going to build krun with systemd support compiled in.
This needs the systemd-devel package in the buildenv image.
Once this change is merged, I'm going to push the new buildenv-image to our image repository.
Then I will submit another PR that changes the krun build to make krun that uses systemd and change km to use the krun that is systemd aware.
Correct me if this is the wrong procedure.

Add systemd-devel to the buildenv fedora image

---

cloud/k8s/deploy/shim/shim.go

For some reason our shim was calling os.exit() in Shutdown instead
of calling the base shim's Shutdown. That's why we were getting
the error in bug #1480.
Brain fart. Mea Culpa.
Fixes: #1480

Call base shim Shutdown instead of direct exit

---

tools/faktory/go.mod
tools/faktory/go.sum

Fix github complaining about faktory using an old version of containerd/containerd
https://github.com/kontainapp/km/security/dependabot/tools/faktory/go.sum/github.com%2Fcontainerd%2Fcontainerd/open

Change faktory to use containerd/containerd 1.4.12

---

.github/workflows/km-ci-workflow.yaml
container-runtime/Makefile

In addition we now build krun with systemd support enabled.
Change krun static build to include systemd support too.
This requires a buildenv-image that contains the systemd-devel package.
Another PR was used to add systemd-devel to buildenv-image.
And, that buildenv-image has been pushed to our azure container repository.

Change km to use krun based on crun 1.4.2

---

cloud/k8s/deploy/kontain-deploy/overlays/kkm/cm-install-lib-kkm.yaml

added krun containerd shim to /bin folder else GKE and EKS give the following problem when deploying kontain based Apps because it can't find the shim.
Events:
Type     Reason                  Age               From               Message
---
Normal   Scheduled               75s               default-scheduler  Successfully assigned default/flaskappkontain-789d6fcd7b-v2tmb to gke-kdocscluster-gke-default-pool-4a60915d-76f3
Warning  FailedCreatePodSandBox  9s (x6 over 75s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: runtime "io.containerd.krun.v2" binary not installed "containerd-shim-krun-v2": file does not exist: unknown

#1528 added krun shim to /bin for GKE and EKS

---

km/Makefile
km/km_elf.h
km/km_main.c
km/km_snapshot.c
km/load_elf.c
tests/buildenv-fedora.dockerfile
tests/buildenv-ubuntu.dockerfile

libelf is a 20K line library that we use a time amout of to read elf files.
We don't use it for writing elf files (core/snapshot). This commit
moves all ELF processing into KM and removes any dependency on libelf.

Remove dependency on libelf - process elf 64 ourselves

---

.github/workflows/km-ci-workflow.yaml
km/km.h
km/km_coredump.c
km/km_exec.c
km/km_filesys.c
km/km_filesys.h
km/km_gdb_stub.c
km/km_management.c
km/km_trace.c
km/km_vcpu_run.c
km/km_vmdriver.c

1. Turn on extended security checks.
2. Fix issues it identifies.
Fixes #1511

enable codeql extended security checks

---

km/km_elf.h
km/km_snapshot.c
km/load_elf.c

Previous attempt to remove dependency on libelf did not remove use of `gelf.h` and associated types. This PR replaces `gelf.h` with `elf.h` and uses `Elf64` types directly instead of GElf types.

remove reference to gelf.h and libelf types

---

km/km_filesys.c
tests/socket_test.c

The `dup` family of system calls were not preserving `sockinfo` inside KM. The new pyflask tests uncovered this bug.
Fixes #1544

preserve sockinfo across dup style syscalls

---

km/km.h
km/km_trace.c
km/km_vcpu_run.c

`km_trace()` family was redone as function instead of macros. Unfortunately that killed function names in the traces, function name became `km_trace` instead of the function that is doing the trace. This one reverts that.

restore function name in log

---

tests/buildenv-fedora.dockerfile

Previous PR to remove NIX from buildenv #1536 didn't get everything. This gets the last bit.

Remove final bits of nix from buildenv

---

.github/workflows/km-ci-workflow.yaml

Krun-static build job now stores persistent artifact. KRUN  is only built if submodule  have been changed, otherwise the exiting artifact from previous build is retrieved and used. 
Job uses new custom action to retrieve and maintain persistent artifact:  ez-leka/persistent-artifact@v1. This custom action will attempt to retrieve  artifact. If found, will download it just like standard download-artifact action and will set output variable of the step 'artifact-status' to 'available'. It will also re-upload artifact to prevent if from expiring. If there is no requested artifact, it will set 'artifact-status' to 'not-found' and return without error. 
'artifact-status' is then used as a condition to determine whether to start run build or if a buid is already available. 
For KRUN-static …

Ez leka/krun separation

---

km/km.h
km/km_elf.h
km/km_main.c
km/km_snapshot.c
km/load_elf.c

No need to buffer Phdr, Shdr, and symbol table string table. stdio is capable of doing that.

ELF load cleanup

---

.github/workflows/km-ci-workflow.yaml

I updated for newer faster VM size (v4) without realizing we are paying for v3 reservation. Revert back.

Trivial: Back to VM size we have reservation for

---

km/Makefile
km/km_guest_asmcode.s
km/km_mem.c
km/km_mem.h
km/km_mmap.c
km/km_snapshot.c
make/custom.mk
tests/km_core_tests.bats

This builds KM as a static PIE, which has the effect of loading in very high memory due to Linux ASLR.
This allows allocating guest memory in KM at address 0, so that physical guest address (PVA) is the same as in km. This is controlled by KM_GPA_AT_16T macro. If defined, km reverts to old physical address schema.
If KM_HIGH_GVA macro is not defined, the virtual guest addresses (GVA) are equal to PVA. If it is defined km reverts to old schema with high GVA up at 128T.
Which means no virtual address translation needed in KM.
Also cleaned up and (I think) simplified memory management code.
Note that the kkm code is not adapted to this yet, so many tests fail. Hence this PR is still WIP.
I'd appreciate a review to make sure I'm not doing something crazy.

km with GVA == KMA

---

km/km.h
km/load_elf.c
tests/.gitignore
tests/Makefile
tests/km_core_tests.bats
tests/run_bats_tests.sh
tests/sigaltstack_test.c
tests/test_helper.bash

- Support programs linked against GLIBC dynamic linker.
- Add tests
Currently the GBD server does not work with programs linked against the GLIBC dynamic linker. This is due to the linker
and LIBC being separate files in GLIBC vs one file in MUSL.

dynamic glibc plus some tests

---

.github/workflows/km-ci-workflow.yaml
Makefile
tests/buildenv-fedora.dockerfile

Added clang-format in the buildenv-image, building it from source. It is not static as I wasn't able to quickly build that with cmake. On the other hand since it is built in the buildenv it refers to all the right libs, so runs fine in CI.
Checked with broken alignment https://github.com/kontainapp/km/runs/6234274961?check_suite_focus=true#step:6:20 and with fixed one https://github.com/kontainapp/km/runs/6234522245?check_suite_focus=true#step:6:18
Also added top level makefile target `clang-format` to run format locally, for those who use the tools without auto formatting.

clang-format in CI

---

km/km.h
km/km_main.c
km/km_mmap.c
km/km_vcpu_run.c
tests/km_core_tests.bats
tests/stray_test.c

This is a proposal to change the default for handling unimplemented systems calls from the current behavior, killing the guest with a `SIGSYS` signal, to returning `-ENOSYS`. (Not Supported). The reasoning for this is experiments in bringing up new apps that attempt to use system calls but are tolerant of ENOSYS. They would have come right up with this implemented where with current behavior, each new system call required a hander to return `-ENOSYS`.
I've included a command line option to go back to the old behavior.

Automatic ENOTSUP for unimplemented system calls

---

km/km_mmap.c
km/km_vcpu_run.c

The auto unrecognized syscall PR and the clang-format PR crossed  and the master CI broke. This fixes that.

fix clang-format errors

---

km_cli/Makefile

When making sure that all executables we install on a node are build as static or static-pie, I forgot this one.

build km_cli as a static

---

km/km_musl_related.c

Switching to Fedora 36 brought gcc 12, which compiles `dlopen()` into slightly different assembly - essentially the instruction in question is shifted by 3 bytes in memory. So inspect both locations and go accordingly.

Support gcc-12 compiled dlopen

---

km/gdb_kvm_x86_64.c
km/km.h
km/km_coredump.c
km/km_coredump.h
km/km_cpu_init.c
km/km_exec.c
km/km_exec_fd_save_recover.c
km/km_filesys.c
km/km_fork.c
km/km_gdb_stub.c
km/km_guest.h
km/km_hcalls.c
km/km_init_guest.c
km/km_main.c
km/km_mem.c
km/km_mem.h
km/km_mmap.c
km/km_signal.c
km/km_snapshot.c
km/km_trace.c
km/km_vcpu_run.c
km/load_elf.c
tests/memslot_test.c

Regular assert uses stderr which is closed. All km messages redirected to km_log_file. This makes asserts use the same file. Without this assert actually segfaults trying to write a message.

km_assert to use our km_log_file instead of stderr

---

.github/workflows/km-ci-workflow.yaml
cloud/scripts/L0-image-provision.sh

There are two changes here. First we change the `kernel.core_pattern` in the L0 base image to `core_%P`, so the km core files are written in the test directory in case km crashed. And second, we keep container after the run completes `DOCKER_RUN_CLEANUP=` so we can copy the files from it for inspection.

save km core in CI

---

.github/workflows/km-ci-workflow.yaml

Per https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
The CI run fails because of krun.static artifact issue, but we can see the codeql works.

TRIVIAL: Move to codeql v2

---

km/km_vcpu_run.c

This is pretty intricate scenario. Depending on which thread - vcpu or gdb - is faster, we occasionally end up with gdb thread waiting for the input from client while all of the vcpus are stopped. Delay sending exit even to gdb after the last vcpu truly exits.
Tested for half a day in a loop on Azure VM.

remove exit race with gdb

---

Makefile
km/km.h
km/km_cpu_init.c
km/km_filesys.c
km/km_fork.c
km/km_gdb_stub.c
km/km_init_guest.c
km/km_signal.c
km/km_signal.h
km/km_vcpu_run.c
tests/km_core_tests.bats

Some of the tests were flaky, particularly the glibc version of them. They occasionally would fail with km locked up in processing of exit_grp. To make CI more reproducible we made these run in a loop for a few times, failing only if all attempts fail. This removes the loops, and fixes the flakiness
The fixes are:
- Two types of sending signal to VCPU - one for payload signal delivery, one for stopping VCPU. Use signal si_value field. It is 8 byte field, so we use 2 bytes for vcpu_id (instead of pointer), and another 2 bytes for flag. If flag is set this is VCPU stopping request.
- Tighten the locks on vcpus for processing vcpu pause and vcpu stop
- Drop pthread_cancel as it requires cleanup
- use pthread_cond_signal() to wake up parked VCPUs
Fixes …

Fix signal delivery, stopping vcpus, tighten vcpu related locks

---

km/km.h
km/km_trace.c
tests/km_core_tests.bats

Allows us to direct km's logging to somewhere else using an environment
variable.  We can use this to tell payloads running in a container to
trace to stderr which can appear in a container's log which we can
retrieve using "docker logs ..." or some similar command.
Added a test for this to the bats km_logging test.

Support KM_LOGTO environment variable.

---

tests/km_core_tests.bats

Some of the tests verify that unusual situations cause a snapshot to
fail.  Those tests don't need to run more than once.

Move some tests out of the basic_snapshot test's main loop.

---

km/km_cpu_init.c

time vcpu_thread can be uninitialized. Check for vcpu_thread validity
before calling km_pkill_no_esrch.
fixes #1638

When a new thread is being created and exit group is called at the same

---

cloud/azure/L0-image.pkr.hcl
tests/run_bats_tests.sh

Because of https://github.com/kontainapp/km/issues/1600 we have occasional CI failures. Disable enlightened VMCS in our L0 image on Azure for now until we have a fix. Also check in tests and refuse to run tests with enlightened VMCS

disable enlightened vmcs in CI, check for it in tests

---

tests/clone_test.c
tests/km_core_tests.bats

CI failure https://github.com/kontainapp/km/runs/7531538116?check_suite_focus=true#step:3:559 shows that raw clone test can fail because of timing in the threads. Child thread might not get a chance to print what the test is expecting before exit. 
Make main thread tell the child thread to proceed and pause. Child thread then prints what it needs to print and does exit.

tighten clone test

---

make/images.mk
tests/km_core_tests.bats

My previous change told make to keep looking in build/opt/kontain/bin.
Change the valgrind_testenv_prep make macro to look there,
not in build/opt/kontain/bin
Also changed the coverage_testenv_prep to get km_cli in
build/opt/kontain/coverage/bin

valgrind builds expect to find km_cli in build/opt/kontain/valgrind/bin

---

km_cli/km_client.c
tests/hello_html_test.c
tests/km_core_tests.bats

Added the -t flag to km_cli to specify whether the payload terminates
after the snapshot is complete.
Fixed a bug where the request length was not supplied with km mgmt requests.

Change km_cli -s to use the snapdir argument

---

tests/hello_html_test.c

Plus add checks for ignored errors in the hello_html_test program.
Decided to fix these "problems" since hello_html_test was involved in the odd km failure where the kernel returned an fd that km thought was already in use.

change variable signedness so we can detect read/write errors

---

km/km_decode.c
tests/decode_test.c

This started as an exercise to increase code coverage of `km_decode.c`. While working on it, I found bugs in `mod/rm` processing and `sib` byte processing. Those are fixed here.

Increase coverage of km_decode.c. Fix bug in mod/rm decode.

---

km/gdb/vcpus.gdb
km/km_cpu_init.c
km/km_main.c
km/km_vcpu_run.c

If `km_vcpu_get()` is called after `exit_grp()` it is possible to get a vcpu that already done `pthread_exit()`. That vcpu will never run hence never exit hence never accounted as exit. km main thread would wait forever.

eliminate race between exit_grp and clone

---

km/km_coredump.h
km/km_filesys.c
tests/snapshot_test.c

The snapshot code would treat eventfd's as though they were epoll fd's
which caused problems if you called epoll_wait() on an eventfd.
So, added code to support snapshoting and recovering eventfd.s
Note that the snapshot code called epoll fd's event fd's so had to
rename some functions too.
Added eventfd testing to the snapshot_test in bats.

Add code to snapshot/recover eventfd's

---

km/km_coredump.h
km/km_filesys.c
tests/km_core_tests.bats
tests/snapshot_fail_test.c

Also support for snapshotting data buffered in a pipe.
The buffered data is stored in the elf note for the write side
of the pipe or socketpair fd's in the snapshot.
The data in the pipe or socketpair is read out to perform the
snapshot and written back into the write side of the pipe so
the application can get its data if it were to resume after the
snapshot request returns.
Changed the bats snapshot_fail_test to now verify that data buffered
in a pipe or socketpair is now available when the snapshot is
restarted.

Add support for snapshoting data buffered in a socketpair

---

km/km_coredump.c

This was causing problems with node tests seeing error:
07:37:26.544067 ioctlfionread 1851 36410.vcpu-0 ioctl FIONREAD on fd -1 failed: Bad file
Ran bats tests and node tests.

Change km coredump to avoid dumping snapshot open file info.

---

tests/buildenv-fedora.dockerfile
tests/km_core_tests.bats

The basic_snapshot test uses the pidof command to find the pid of a command it wants to snapshot.  When the bats tests run with concurrency enabled pidof can return multiple pids which isn't handled. Add a small loop to traverse the list of pids returned by pidof to find which pid we need for the test.

Change bats basic_snapshot to tolerate multiple pids from pidof

---

km/km_filesys.c

The dup detection that was implemented is based on inode # and dev being the same for dups, _**and not the same for non dups**_
Well, turns out, both end of the pipe have the same inode #. Also, all of the fds in the same eventfd group have the same inode #.
Also all kvm fds other than the first `/dev/kvm` open are the same inode #. The latter doesn't affect us, just an observation.
[before.txt](https://github.com/kontainapp/km/files/9529958/before.txt)
This restrict the inode # based dup check to files and regular sockets. Simple node snapshot test passes.

limit inode based dup check to files and sockets only

---

km/km_coredump.c
km/km_coredump.h
km/km_exec_fd_save_recover.c
km/km_filesys.c
km/km_filesys.h
km/km_filesys_private.h
tests/km_core_tests.bats
tests/snapshot_test.c

This is better/correct way to handle duped fd.
During the run we monitor all sources of duped fds - dup{,2,3} and F_DUPFD fcntl, also we monitor close. That allows us to maintain a table of dup groups. Each group is a list of fds that are dups of each other. There could be many of them.
On snapshot we create a new note to pass these groups along. On restore we restore that before fds. When we restore fds we check with the duped groups. FOr each fd that is restored first in the group we restore in normally. But for the subsequent ones we do the dup.
tested with normal test extended a bit. Also checked node snapshot works. Will be testing more, likely adding more tests. But appreciate a review.

Revisited duped fd processing

---

km/km_filesys.c
payloads/java/.gitignore
payloads/java/Makefile
payloads/java/test-fedora.dockerfile
payloads/java/test_java.bats
payloads/node/Makefile
payloads/node/scripts/test-run.sh

Adds node snapshot tests both on local machine and on CI.
Add java snapshot on local machine only. Java has no real tests on CI because it uses bats. Need to enable that in java directory.
Discovered bug in recovery of open sockets. We populate our filesys structure BUT we don't open file on the host. Next open file on the host will conflict with the our data. The test for this is Java snapshot test which I only ran locally (see above).
I'd really like to push this ASAP and figure out CI in Java after that.

Test payload snapshots

---

km_cli/km_client.c
tests/km_core_tests.bats

km_cli -s will now supply no snapshot file name to km. So km will use the value specified with its --snapshot command line argument.
Changed the bats continue_after_snapshot to work with this old way of doing things.

Change km_cli -s to work like it used to.

---

km/km_management.c
tests/km_core_tests.bats
tests/test_helper.bash

${VALGRIND} is not quoted in some places in km_core_tests.bats causing shell tests to fail which is interpreted as a false test result. 
Listening on the management pipe is potentially delayed in time after binding the listening address.  
Leaving a window where the mgmt pipe exists but nothing is listening for connection attempts.

Fix script quote issues and km mgmt listen issue.

---

km/km_coredump.c
km/km_coredump.h
km/km_filesys.c
km/km_filesys.h
km/km_management.c
km/km_signal.c
km/km_snapshot.c
km/km_trace.c
km_cli/km_client.c
tests/km_core_tests.bats

To allow a payload to continue running after a failed snapshot request we need to change km_dump_core to return an error instead of aborting/exiting km.  All of the functions called by km_dump_core were changed to return an error on failure.
Changed the callers of km_dump_core() to handle error returns.

Change km_dump_core() to return an error on failure.

---

payloads/node/scripts/test-run.sh

Simply remove the sleep and try the snapshot right after curl. The first attempt is likely to fail, but the subsequent one succeeds

retry failed node snap instead of simply sleep 1

---

km_cli/km_client.c

Formerly the -c arg was used to do partial matches which would match other commands when that is not what was intended.

Change km_cli -c to do exact command name matches

---

tests/cmd_for_attach_test.gdb
tests/gdb_lots_of_threads_test.c

I have found that threads created by pthread_create() are not running immediately and can't be pthread_join()'ed until they are running. This fix is being put in because the gdb_attch bats test failed because gdb info threads reported all threads were on vcpu-0. I don't understand how that would happen but I think those new threads were not ready to be debugged because pthread_create() for the vcpu threads in km were not done with their work.
Since this test does do pthread_join() we should wait for the threads to be running before doing the join so this change doesn't hurt.

Change gdb_lots_of_threads.c to wait for all threads to be running

---

.github/actions/configure-krun/action.yaml
.github/workflows/km-ci-workflow.yaml
Makefile
cloud/scripts/L0-image-provision.sh
container-runtime/Makefile
container-runtime/docker_config.sh
container-runtime/podman_config.sh
docs/build.md
make/locations.mk

No change in main-stream product. Strictly dev environment convenience. 
------------------------
Configure docker and podman to use development build of run and km (build/opt/kontain/bin)
```
make install-dev-runtime RUNTIME=<give it a distinct name>
```
To remove this configuration:
```
make uninstall-dev-runtime RUNTIME=<name from prev step>
```
Now docker and podman will try to use krun and km when the "--runtime your-runtime-name" argument is supplied with "docker run" or "podman run".
Without --runtime, runc will be the default container runtime.
To test payloads with development runtime
```
make -C payloads validate-runenv-image RUNTIME=your-runtime-name
```

Ez leka/local dev

---

km/km.h
km/km_filesys.c
km/km_trace.c
tests/km_core_tests.bats

The continue_after_snapshot bats test occasionally fails with this message:
```
07:12:47.612374 km_add_guest_fd_inte 241  vcpu-0  file slot 1 for (null) is taken unexpectedly
```
We don't know what is wrong here.  To maybe get some clues I've changed km's options to generate debug tracing into a file for this test.
I've also changed the km code that generates this message to abort instead of just exiting with a message.
Hopefully in a week or 2 we will run into the problem again and there will be some trace data to look at.

Add debug for the bats continue_after_snapshot test

---

km/km_musl_related.c
tests/km_core_tests.bats

The ubuntu gcc 11.2 dlopen looks like this:
Dump of assembler code for function dlopen:
0x00000000002625bc <+0>:     endbr64
0x00000000002625c0 <+4>:     push   %r15
0x00000000002625c2 <+6>:     push   %r14
0x00000000002625c4 <+8>:     push   %r13
0x00000000002625c6 <+10>:    push   %r12
0x00000000002625c8 <+12>:    push   %rbp
0x00000000002625c9 <+13>:    push   %rbx
0x00000000002625ca <+14>:    sub    $0x1b8,%rsp
0x00000000002625d1 <+21>:    mov    0x4f918(%rip),%rax        # 0x2b1ef0 <head>
0x00000000002625d8 <+28>:    mov    %rdi,0x20(%rsp)
0x00000000002625dd <+33>:    mov    %esi,0x14(%rsp)
0x00000000002625e1 <+37>:    movq   $0x0,0x60(%rsp)
0x00000000002625ea <+46>:    test   %rdi,%rdi
0x00000000002625ed <+49>:    je     0x262d75 <dlopen+1977>
We need to get the head of the …

Ubuntu gcc 11.2 gdb_sharedlib bats test fails

---

km_cli/km_client.c

km_cli allocated a 200kb buffer to hold /proc/NNN/net/unix to do its work.  If that isn't large enough you may not be able to find a km process mgmt pipe file.
Changed the code to grow the buffer as needed.

Change km_cli to read unlimited size /proc/NNN/net/unix files

---

km/km.h
km/km_filesys.c
km/km_main.c

keep track of the latest connected socket and don't trigger payload shrink if it is still open

don't shrink if there is connected socket

---

km/km_filesys.c

light_snap_listen() decodes what is stored in the SNAP_LISTEN_PORT env var.  If it can't decide the variable, it just drops thru to the listen call with an invalid fd which causes listen() to fail. This change adds code to print a message showing the contents of SNAP_LISTEN_PORT before exiting km.

Give better error when the SNAP_LISTEN_PORT env var can't be decoded

---

tests/km_core_tests.bats

These 2 tests timeout periodically in the CI bats tests. These tests don't do much but the cloud is punishing them once in a while and the tests time out.
So, increase the timeouts to 10 seconds from 5 seconds.

Increase the CI timeout for the bats popen and files_on_exec tests

---

km/km.h
km/km_management.c
km/km_vcpu_run.c

The cloud can leave km threads preempted for a long time.  We have seen cases where the mgmt thread is running before the payload is started, allowing snapshot requests when km is not ready to perform them. This change prevents attempting snapshots until after the payload is started.

Have km management thread fail requests until the payload is started

---

payloads/java/test_java.bats

The java payloads ci regularly fails like this:
``` 
not ok 4 Java SpringBoot snapshot
(from function `assert_success' in file scripts/bats-assert/src/assert.bash, line 114,
in test file km-bats-8.dynamic, line 66)
`assert_success' failed with status 7
07:25:57.299979 km_set_snapshot_path 51   km      Setting snapshot path to kmsnap
07:25:57.317530 km_mgt_init          161  km      snapshot pipe name is /tmp/xxx.160
.   ____          _            __ _ _
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/  ___)| |_)| | | | | || (_| |  ) ) ) )
'  |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot ::        (v2.2.0.RELEASE)
2022-12-09 07:26:04.727  INFO 170 --- [           main] c.e.restservice.RestServiceApplication …
```

Change curl command to stop suppressing messages

---

payloads/java/test_java.bats

Apparently starting springboot up in the github runner can take quite a while.  So we have curl wait for up to 2 minutes to connect to the springboot process before failing.  It formerly waited 20 seconds but that failed occasionally.

Increase the curl timeout in the Java SpringBoot snapshot bats test

---

km/km_decode.c
km/km_main.c
km/km_snapshot.c

Todays CI failure shows a km trace that has both a snapshot generation and snapshot resume all run together.  To help us realize what is happening the next time we see this there are km traces now for begin and end of snapshot generation and resumption.
Plus the message for an uninterpreted opcode has been changed to include both the PC for the instruction and the first 6 bytes of the instruction.

Improve snapshot messages and uninterpreted opcode message

---

km/km.h
km/km_filesys.c
km/km_main.c

Instead of using timeout as indicator of payload be done. use only accepted socket count, shrink the payload when that drops to zero.
The old behavior is preserved - if timeout is positive it is treated as timeout in milliseconds. But if it is negative the counter only approach is used.

light snap start with payload shrink on the last accepted socket close

---

km/km_decode.c
tests/decode_test.c

Addeded support for the VEX 2 and 3 byte instruction prefixes. Also added a smoke test for these prefixes to the bats decode_test. Since the XOP prefix is similar to the VEX 3 byte prefix, it is plumbed in but its tables of opcodes that reference memory has not been filled in.

Add support for vex instruction prefix to km_decode.c

---

km/km_filesys.c

When we restarting from snapshot we treat previously connected socket as error, simply telling the app ECONNRESET. That socket was not accepted in the snapshot, it was accepted before snapshot was taken. Hence we should not count it as real close for the purposes of tracking active connected sockets.
The condition is rare hence we haven't seen it before. Payload (like springboot app) is done with the request, response is sent, **but** the socket is not closed yet. Then after snapshot restart the close comes, and our accepted socket counting is wrong. So now we check for that state when count active accepted sockets.

don't count accepted pre-snapshot sockets

---

tests/km_core_tests.bats

expr has a failure exit status if the expression it is processing evaluates to zero.
Which was causing bats to decide that the expr command failed.

Change the multilisten test to stop using expr

---

km/km_filesys.c
km/km_main.c
tests/km_core_tests.bats

This fix allows to set an environment variable for km when running snapshot. For instance, unset LD_PRELOAD whn running valgrind, or KM_VERBOSE.

Warn instead of error setting environment for snapshot, enable valgrind for snapshot tests

---

km/km_hcalls.c

After this morning nginx conversation I tried it. The issue was with getgroups incorrectly checking for `list == NULL`. In fact it is allowed to be NULL if size is 0. 
>  If size is zero, list is not modified, but the total number of supplementary group IDs for the process is returned.  This allows the caller to  determine the size of a dynamically allocated list to be used in a further call to getgroups().
nginx runs OK with this fix

setgroups, fix logic with size == 0

---

km/km_filesys.c
km/km_filesys.h
km/km_filesys_private.h
km/km_hcalls.c
tests/env_test.c

Add support for setuid()/setgid() syscalls.
Using serge's implementation from another in progress changeset of his.
I looked at a km trace that serge got from running ngnix under km. We saw several things and this changes addresses some of them. We saw trying to add an fd that was already in use.  This seems to come from sendmsg/recvmsg using SCM_RIGHTS to pass fd's between processes.
I also see that nginx tries to use the timerfd_create() family of syscalls, so added those.
nginx also tries to use io_setup() et al syscalls.  I've added the stubbed out functions to support this but implementation is needed.

Add support for timerfd syscalls, fix sendmsg() logging.

---

km/km_hcalls.c

The kernel uses the length of a length/address pair to decide if it should validate the address.  km's sendmsg/recvmsg was not following this rule.
Not that this rule is not absolute.  The msg_name and msg_namelen fields of the msghdr don't follow this.

Fix km sendmsg address validation

---

km/km.h
km/km_coredump.c
km/km_hcalls.c
tests/aio_test.c
tests/km_core_tests.bats

The io_setup(), io_submit(), io_getevents(), io_cancel(), and io_destroy() hypercalls are added to km with this change. The bats aio_test program is added to exercise the hypercalls. I can't figure out how to make io_cancel() work.  It seems like the io request being canceled must be active.  If the io has completed, I assume it is nolonger cancelable and it returns an error code that doesn't tell me the io request has completed.
Putting this out for people to look at and comment on.

Add the aio io_*() syscalls to km and a simple test program

---

km/km.h
km/km_coredump.c
km/km_coredump.h
km/km_filesys.c
km/km_gdb_stub.c
km/km_main.c
km/km_snapshot.c

If a new km environment variable called KM_GDB_WAIT_BEFORE_SNAP_RESUME is supplied to the instance of km that is resuming a snapshot, km will pause to wait for gdb to attach before starting the snapshot.

Allow a gdb to attach to a snapshot just before the snapshot is started

---

km/km_guest_asmcode.s

To use in GDB: `add-symbol-file $WROKSPACE/km/build/km/km_guest_asmcode.o -o 0x8000008000`

Add CFI directives to guest code. Allows stack trace through SYSCALL.

---

km/km_mem.c

Don't assign a filename to the vvar and vdso regions in the km memory busy map. km was assigning the non-filenames [vvar] and [vdso] to the vdso regions which apparently prevented gdb from checking to see if they were the vdso area.
A quick way to test is run gdb on a payload coredump and then run the "disassem gettimeofday" command.
You will see symbols like __vdso_gettimeofday in the output which tells you gdb was able to access the symbols stored in the vdso pages.

Fix km to allow gdb to use the symbols in the vdso pages

---

km/Makefile
km/km_coredump.c
km/km_coredump.h
km/km_filesys.c
km/km_hcalls.c
km/km_iocontext.c
km/km_iocontext.h
km/km_snapshot.c
tests/aio_test.c
tests/km_core_tests.bats

The io_setup() syscall creates an asynch i/o context and returns it to the caller. The payload has no way to control what value for the context is returned.  For snapshot of asynch io to work we must allow to the payload to continue using the context it received before a snapshot was taken.  To accomplish this km generates its own io contexts and maps them to the ones created by the kernel.  Only km generated io contexts are passed to the payload.  So when a payload uses an io context km translates that value to the kernel value returned with io_setup() before forwarding asynch io requests to the kernel.
These km generated io contexts are saved in a new elf note in snapshot files so that the context can be restored when the snapshot is resumed and then continue to be used by the payload. …

Add snapshot support for contexts created by io_setup().

---

tests/km_core_tests.bats

The km_with_timeout() shell function keeps adding things to the KM_ARGS shell variable if we don't run each instance in a subshell with the bats run command.  When running bats with valgrind this will add "--copyenv=LD_PRELOAD" to KM_ARGS each time km_with_timeout is run in the main shell which will cause km to fail complaining about multiple instances of the --copyenv flag.
I'm not sure if this is a bug in tests/test_helper.bash (which is where km_with_timeout lives) or a bug in tests/km_core_tests.bats since we don't consistently use run with km_with_timeout.

bats aio_test needs to run km_with_timeout in subshell with valgrind

---

km/km_filesys.c

We occasionally see file mode mismatches when a payload snapshot is resumed.  This causes the snapshot resume to fail. In one case the original file is a regular file, after the snapshot is resumed the file is a char special file.
I'm assuming the fd is one of the stdio fd's.  If so, we can skip this check.
For now, add the fd to the message to see if my guess is correct.

Log payload fd when recovered file has mismatched file mode

---

include/km_hcalls.h
km/km_hc_name.c
km/km_hcalls.c
km/km_main.c
km/km_snapshot.c
km/km_snapshot.h
lib/libkontain/libkontain.c
lib/libkontain/libkontain.h
tests/km_core_tests.bats
tests/snapshot_test.c

These calls were used by a prototype FAAS I did a few years ago. They are no longer needed.
I did these changes while waiting for paul to deliver his nvidia changes for snapshot/restore.

remove obsolete snap_getdata/snap_putdata hypercalls

---

km/km_coredump.c
km/km_filesys.c
km/km_filesys.h
km/km_snapshot.c
tests/.gitignore
tests/snapshot_fail_test.c

pytorch demo https://github.com/kontainapp/km-demo/pull/8 does fork two short lived children. Which disables snapshot, but in fact there is no reason. This change relaxes the check a little bit.
Changed bats test to allow this too.

relax check for fork on snapshot

---

km/km_filesys.c

Noticed zero sized malloc on some snapshot restarts.

check for zero size dup data, skip malloc

---

tests/km_core_tests.bats

The bats gdb_sharedlib test tries to use km options --putenv and --copyenv together which is not allowed.
Skip this test for that combination.

Dont run gdb_sharedlib test with valgrind and glibc_dynamic

---

km/km_hcalls.c

km crashes when negative values are passed for vlen.

fix sendmmsg vlen parameter type mismatch

---

km/km_coredump.c

km_core_last_load_adjust() was returning an int, so if brk area is longer than 2GB the size calculation is wrong

correct core size calc for > 2GB brk area

---

km/km_snapshot.c

Some code in snapshot restore uses the hardcoded value 256 * GIB to decide if it is dealing with memory allocated with the brk() system call or memory allocated with mmap().
It turns out machine.brk is saved in the coredump/snapshot and is restored when a snapshot is recovered, so we can use that value to make decisions rather than the hardcoded 256gb value during the remainder of snapshot restore.

Use restored machine.brk value during snapshot restore

---

km/km_mem.c
tests/brk_test.c

We found problems when shrinking the break (brk() system call) from 1.5gig down to .5gig.
It looks like the page tables were not being updated properly when this happened.
This change hopefully fixes this problem and adds some tests to verify that memory is or is not accessible after the break is shrunk.

Fix faults caused by large reductions in the break size

---

km/km_filesys.c

We got bitten by lseek to the end of 7GB file. I went through the file to check for other calls.

use the correct syscall return types

---

container-runtime/podman_config.sh

turns out docker-init executable installation location varies widely and unpredictable between fedora, ubuntu and various versions of docker. To avoid chasing it, install tini-static as a separate package and use that one instead.

install and use tini-static instead of docker init

---

tests/test_helper.bash

Fixed https://github.com/kontainapp/km/issues/1223
Turns out when bats run in parallel mode the stdin into tests is redirected from `/dev/null` and interactive commands gets EOF right way. But in singly threaded mode stdin reads from tty. When quitting gdb it asks:
```A debugging session is active.
Inferior 1 [Remote target] will be detached.
Quit anyway? (y or n)
```
and hangs in that, causing the timeout.
Put `--batch` in gdb command line to stop that.

gdb in tests in batch mode

---

km/km_vcpu_run.c
tests/km_core_tests.bats

Turns out modern KVM `ioctl (KVM_RUN)` _sometimes_ returns -errno and keeps proper errno untouched. According to `man ioctl()` it should return -1 and set `errno` in case of an error. However I observe that ioctl returning -14 (EFAULT) and errno is left untouched.

handle ioctl errno

---

km/km.h
km/km_filesys.c
km/km_hc_name.c
km/km_trace.c

The memory trace macro is km_info_mem().
The sockaddr trace macro is km_info_sockaddr().
There is only support for AF_* values I've run into. If km_info_sockaddr() runs into an AF_ value it can't handle it produces a trace like this:
"%s unhandled address family: %d, fixme!"
The km_info_mem() produces a dump like this:
OOOOOO: XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX  *AAAAAAAAAAAAAAAA* 
Where "000000" is the offset in hex from the beginning of the memory area to be dumped.
Where XX is the hex value of a byte.
And "A" is the ascii for a byte.  If the byte is not printable a dot is displayed.
Added a km trace category named "network".
Use the name network with the km -V command line flag. 
Use the symbol KM_TRACE_NETWORK in km_info() macro calls.
Add tracing of the sockaddr's passed …

Add facilities to trace memory contents and sockaddr's

---

tests/km_core_tests.bats
tests/sendmsg_test.c

It is currently using 2 fixed port numbers which can cause EADDRINUSE errors sometimes.
Chnaged sendmsg_test to use port numbers assigned it by the bats test script.

Change sendmsg_test to use assigned port numbers

---

tests/km_core_tests.bats
tests/sendmsg_test.c

Valgrind doesn't let us use the --putenv argument to km which the fix to sendmsg test was using.
Changed the sendmsg test to pass the port number in as the first argument.

Change bats sendmsg test to stop using --putenv

---

km/Makefile
km/km_guest_asmcode.s
km/km_hcalls.c
make/images.mk
make/locations.mk
tests/km_core_tests.bats

Added cfi directives, enabled tests in bats.
In order for this to work need to do
> --ex="add-symbol-file ../build/km/km_guest_asmcode.o -o 0x8000008000"

fix gdb backtrace with glibc
